import { NextRequest } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';
import {
  ok, created, badRequest, serverError,
  pseudonymise, type MembershipStatus
} from '@/lib/types';
import { requireApiRole } from '@/lib/staff-auth';

// Roles allowed to see/manage the member directory. Member records
// carry pastoral (prayer group, follow-up status) and administrative
// (contact details, membership status) data, so both categories —
// plus elders, who oversee both — are included.
const MEMBER_DIRECTORY_ROLES = ['administrative', 'pastoral', 'elder'] as const;

// ============================================================
// GET /api/members
// Returns member list. Role determines what fields are returned.
// Query params:
//   ?status=active          filter by membership status
//   ?prayer_group_id=uuid   filter by prayer group
//   ?family_unit_id=uuid    filter by family unit
//   ?search=john            search by name or phone
//   ?report=true            returns pseudonymised format only
// ============================================================

export async function GET(req: NextRequest) {
  try {
    const auth = await requireApiRole([...MEMBER_DIRECTORY_ROLES]);
    if ('error' in auth) return auth.error;

    const { searchParams } = req.nextUrl;
    const status        = searchParams.get('status') as MembershipStatus | null;
    const prayerGroupId = searchParams.get('prayer_group_id');
    const familyUnitId  = searchParams.get('family_unit_id');
    const search        = searchParams.get('search');
    const reportMode    = searchParams.get('report') === 'true';

    // requireApiRole() above confirms the caller is a signed-in staff
    // member with an allowed role — that's the access-control boundary.
    // church_id itself still comes from the env var: this is a single-
    // church deployment and StaffMember doesn't carry a church_id yet
    // (see improvement-plan Task 0.3, multi-tenant churches table).
    const churchId = process.env.SHAURI_MOYO_CHURCH_ID;
    if (!churchId) {
      return serverError('Church ID not configured.');
    }

    let query = supabaseAdmin
      .from('church_members')
      .select(`
        id,
        member_number,
        first_name,
        last_name,
        preferred_name,
        gender,
        date_of_birth,
        phone,
        email,
        membership_status,
        baptism_date,
        visitor_type,
        follow_up_status,
        is_prayer_group_leader,
        digital_statements_opted_in,
        attendance_prompt_opted_in,
        announcements_opted_in,
        created_at,
        family_unit_id,
        prayer_group_id,
        family_units!church_members_family_unit_id_fkey ( family_name ),
        prayer_groups ( name, area )
      `)
      .eq('church_id', churchId)
      .order('last_name', { ascending: true });

    if (status)        query = query.eq('membership_status', status);
    if (prayerGroupId) query = query.eq('prayer_group_id', prayerGroupId);
    if (familyUnitId)  query = query.eq('family_unit_id', familyUnitId);
    if (search) {
      query = query.or(
        `first_name.ilike.%${search}%,` +
        `last_name.ilike.%${search}%,` +
        `phone.ilike.%${search}%,` +
        `member_number.ilike.%${search}%`
      );
    }

    const { data, error } = await query;
    if (error) {
      console.error('Members GET error:', error);
      return serverError('Could not retrieve members.');
    }

    // Report mode: return pseudonymised data only
    if (reportMode) {
      const pseudonymised = (data || []).map(m => ({
        member_number:     m.member_number,
        display_name:      pseudonymise(m.first_name, m.last_name, m.member_number),
        membership_status: m.membership_status,
        prayer_group:      (m.prayer_groups as any)?.name ?? null,
        family_unit:       (m.family_units as any)?.family_name ?? null,
      }));
      return ok({ members: pseudonymised, count: pseudonymised.length });
    }

    return ok({ members: data, count: data?.length ?? 0 });

  } catch (err) {
    console.error('Members GET exception:', err);
    return serverError();
  }
}

// ============================================================
// POST /api/members
// Creates a new member record.
// Member number is auto-generated by the database trigger.
// ============================================================

export async function POST(req: NextRequest) {
  try {
    const auth = await requireApiRole([...MEMBER_DIRECTORY_ROLES]);
    if ('error' in auth) return auth.error;

    const body = await req.json();

    const {
      first_name,
      last_name,
      gender,
      date_of_birth,
      phone,
      email,
      physical_address,
      membership_status = 'active',
      baptism_date,
      date_joined,
      family_unit_id,
      prayer_group_id,
      visitor_type,
      digital_statements_opted_in = false,
      attendance_prompt_opted_in  = false,
      announcements_opted_in      = true,
      notes,
    } = body;

    // Validation
    if (!first_name?.trim()) return badRequest('First name is required.');
    if (!last_name?.trim())  return badRequest('Last name is required.');

    const churchId = process.env.SHAURI_MOYO_CHURCH_ID;
    if (!churchId) return serverError('Church ID not configured.');

    // Check for duplicate phone number within this church
    if (phone) {
      const { data: existing } = await supabaseAdmin
        .from('church_members')
        .select('id, first_name, last_name, member_number')
        .eq('church_id', churchId)
        .eq('phone', phone.trim())
        .single();

      if (existing) {
        return badRequest(
          `A member with this phone number already exists: ` +
          `${existing.first_name} ${existing.last_name} (${existing.member_number})`
        );
      }
    }

    const { data, error } = await supabaseAdmin
      .from('church_members')
      .insert({
        church_id: churchId,
        first_name:                     first_name.trim(),
        last_name:                      last_name.trim(),
        gender:                         gender ?? null,
        date_of_birth:                  date_of_birth ?? null,
        phone:                          phone?.trim() ?? null,
        email:                          email?.trim().toLowerCase() ?? null,
        physical_address:               physical_address ?? null,
        membership_status,
        baptism_date:                   baptism_date ?? null,
        date_joined:                    date_joined ?? null,
        family_unit_id:                 family_unit_id ?? null,
        prayer_group_id:                prayer_group_id ?? null,
        visitor_type:                   visitor_type ?? null,
        digital_statements_opted_in,
        attendance_prompt_opted_in,
        announcements_opted_in,
        notes:                          notes ?? null,
      })
      .select()
      .single();

    if (error) {
      console.error('Member create error:', error);
      return serverError('Could not create member record.');
    }

    return created({
      message: `Member created successfully.`,
      member:  data,
    });

  } catch (err) {
    console.error('Member POST exception:', err);
    return serverError();
  }
}
